name: Require README update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pass-always:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Compatibility check to satisfy required status; actual README version injection handled elsewhere."