name: Require README update

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  pass-always:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Compatibility check to satisfy required status across all branches."