name: README auto-version (date+hash)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inject-and-pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Inject version (skip if bot commit)
        if: github.actor != 'github-actions[bot]'
        run: |
          DATE=$(date -u +%F)
          HASH=$(git rev-parse --short HEAD)
          sed -i -E "s/(<!--VERSION_START-->).*(<!--VERSION_END-->)/\1${DATE}+${HASH}\2/" README.md
          if ! git diff --quiet README.md; then
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add README.md
            git commit -m "chore(ci): inject version ${DATE}+${HASH} into README"
          fi
      - name: Push changes (push events only)
        if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
        run: git push
      - name: Done
        run: echo "README version ensured."